version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: financial-planner
        uid: 1000
    container_name: financial-planner-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - financial-planner
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: financial_planners
      DB_USERNAME: financial_planner
      DB_PASSWORD: secret

  db:
    image: mariadb:latest
    container_name: financial-planner-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: financial_planners
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: financial_planner
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:
      - financial-planner

  nginx:
    image: nginx:alpine
    container_name: financial-planner-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - financial-planner
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: financial-planner-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: financial_planner
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    networks:
      - financial-planner
    depends_on:
      - db

networks:
  financial-planner:
    driver: bridge

volumes:
  dbdata:
    driver: local
